### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Dedvin** [GreenfieldMC/Greenfield-Texturepack#1]
Can you make an version of the texture pack or just change the texturepack so that it dont edit the particles, especialy stone, sand and snow. It is essential for a plugin on my server to work properly. Because when you edit the particles it disables the plugins particles. If you wanna know exacly what plugin i'm talking about: https://www.spigotmc.org/resources/wind-%E2%AD%90-add-completly-custom-wind-to-your-minecraft-server-%E2%AD%90-25-sale.77232/
If you dont wanna click the link, it is called "Wind" and it is a spigot plugin.

**Comment by Bluecolty** [comment]
Hi, thanks for reaching out. As far as I know, there is no easy way to change the particle effects for our pack outside of creating new block models and mapping the particle effects to the default textures. While we want to work to stay open minded to fan suggestions and requests, its hard to cater to only a few people with an issue that's rather niche. That solution may end up causing more problems though, so the only other option is to delete the stone, sand, and snow textures in our pack which can be found with a bit of file exploring. The location for these textures is at assets>minecraft>textures>block, and then you'll have to search for stone.png, sand.png, and snow.png. This should provide you with a better fix than the issue you're having now, although it isn't perfect. 

I'd also reccomend joining the Greenfield Minecraft discord server so we can help you a bit better. 
[https://discord.gg/jA4AyqCu9g](https://discord.gg/jA4AyqCu9g)

**Comment by NJDaeger** [comment]
Going to also add, if you'd want to have other particles, you could theoretically create a second resource pack that overlays on top of ours to re-add particles into the game. We remove a lot of them so we don't have to deal with issues on the server.

I believe the particle that sand/gravel/stone uses is also the same one that Redstone uses has been removed due to their particles making some of our builds worse.

**Comment by Dedvin** [comment]
After a long time of testing i have found the file causing the error. It is called generic_6.png

**Comment by Dedvin** [comment]
I did not understand that last part NJDaeger.

**Comment by NJDaeger** [comment]
> I did not understand that last part NJDaeger.

The particle that sand and gravel use when they are floating is the same particle as the redstone particle. We removed the particle from our resource pack because they were an annoyance.
