### ISSUE TITLE
Metalization of item frame

### ISSUE THREAD

**Issue by Bluecolty** [GreenfieldMC/Greenfield-Texturepack#11]
**What is the texture you would like added?**
Turn the item frame into a metalized silver color

**Should this texture be based on an existing block? If so, what block?**
This texture should be based off the iron rails

**Provide an image reference of the material/texture being used in real life. (More than one, if possible)**
Not applicable

**Additional context**

Message by Ajeb in builders chat

**Comment by NJDaeger** [comment]
I think we did this?
