### ISSUE TITLE
Red Candle

### ISSUE THREAD

**Issue by NJDaeger** [GreenfieldMC/Greenfield-Texturepack#12]
**Resource pack version**
1.17 Pack

**Minecraft version**
1.17

**Describe the bug**
The red candle (LED spotlight) has a texture bug where it has light gray lines on the edges of the light. Those shouldn't be there.

**What is the block/entity this texture is affecting?**
Red candle

**What do you expect to see?**
To not have the light-colored lines on the edges of the block.

**Screenshots**
![image](https://user-images.githubusercontent.com/18237863/127249252-4cc0ab2e-5062-4aaf-ac21-14b26bd40130.png)

**Comment by Coothy** [comment]
Optifine bug.
