### ISSUE TITLE
Redo Vanilla Carrot/Potato/Beetroot 

### ISSUE THREAD

**Issue by Coothy** [GreenfieldMC/Greenfield-Texturepack#15]
**What is the texture you would like added?**
Redone crop textures

**Should this texture be based on an existing block? If so, what block?**
Staples' plant textures

**Provide an image reference of the material/texture being used in real life. (More than one, if possible)**
- https://media.discordapp.net/attachments/857013841501880371/867609818747764776/caption.gif
- https://farm6.static.flickr.com/5025/5728853850_a3bbb14083_z.jpg
- https://i.ytimg.com/vi/k3qvdnpSY5I/maxresdefault.jpg

**Additional context**
Should probably stay as said crops since they are already used around the map.

**Comment by NJDaeger** [comment]
God what even are those images

stunning
