### ISSUE TITLE
Brown Candle missing particle texture. 

### ISSUE THREAD

**Issue by JacobKazias** [GreenfieldMC/Greenfield-Texturepack#17]
**Resource pack version**
1.17

**Minecraft version**
1.17
**Describe the bug**
Brown Candle has missing particle texture when broken. 

**What is the block/entity this texture is affecting?**
All Brown Candles

**What do you expect to see?**
Colour appropriate particles. 

**Screenshots**

**Comment by NJDaeger** [comment]
this was fixed in 1.20
