### ISSUE TITLE
Hanging roots beard hat 

### ISSUE THREAD

**Issue by Coothy** [GreenfieldMC/Greenfield-Texturepack#22]
**Resource pack version**
1.17

**Minecraft version**
1.17

**Describe the bug**
Hanging roots aren't a beard when worn as hat

**What is the block/entity this texture is affecting?**
Hanging roots

**What do you expect to see?**
When worn as a hat, the hanging roots are modeled on your chin like a scraggly (jacob) beard

**Screenshots**
https://cdn.discordapp.com/attachments/855623063243456542/888645136291094569/2021-09-18_00.36.07.jpg

**Comment by NJDaeger** [comment]
I think i addressed this
