### ISSUE TITLE
Deep fry

### ISSUE THREAD

**Issue by goldygolden** [GreenfieldMC/Greenfield-Texturepack#26]
**What is the texture you would like added?**
Deep frying Oil

**Should this texture be based on an existing block? If so, what block?**
powdered snow (specifically the couldron variant if you can} or lava

**Provide an image reference of the material/texture being used in real life. (More than one, if possible)**
![image](https://user-images.githubusercontent.com/92544704/137548837-936d3a5a-056d-46bc-8966-2c9080b91722.png)

**Additional context**
Would be cool if it was added for restaurants, and other food buisnesses. im not sure how you guys would do it but i guess it could be yellowish orange with bubbles.

**Comment by NJDaeger** [comment]
Done as a part of 1.20
