### ISSUE TITLE
Birch paneling

### ISSUE THREAD

**Issue by ok0wen** [GreenfieldMC/Greenfield-Texturepack#32]
**What is the texture you would like added?**
Birch Paneling 

**Should this texture be based on an existing block? If so, what block?**
Not sure which block

**Provide an image reference of the material/texture being used in real life. (More than one, if possible)**
https://patch.com/img/cdn20/users/22883275/20210305/043132/styles/patch_image/public/starbucks-fb___05163029290.png
https://i.imgur.com/CP7j2kg.png

**Additional context**

**Comment by NJDaeger** [comment]
This was somewhat hit with the Stripped Mangrove Logs texture
