### ISSUE TITLE
New sounds

### ISSUE THREAD

**Issue by HypoTrance** [GreenfieldMC/Greenfield-Texturepack#34]
**What is the texture you would like added?**
Vine boom audio for falling anvils and tnt explosions

**Should this texture be based on an existing block? If so, what block?**
Audio for anvil drop sound and tnt explosion sound

**Provide an image reference of the material/texture being used in real life. (More than one, if possible)**
Eg. [this](https://i.pinimg.com/originals/8a/0e/cd/8a0ecd5c6cbbefca56fe87fb3714aa65.jpg) or [this](https://st.hzcdn.com/fimgs/pictures/exteriors/stonecraft-brand-man-made-stone-veneer-stone-brighton-stone-and-fireplace-inc-img~ae919c790745ccc1_0704-1-2ec4b60-w312-h312-b0-p0.jpg) https://www.youtube.com/watch?v=_vBVGjFdwk4 - Vine boom sound effect 

**Additional context**
Eg. Any additional information that would help us pinpoint what this block should look like and function as.
vinew boom

**Comment by NJDaeger** [comment]
This feature could potentially add a copyright issue. To avoid this, I don't think we can reliably add these without putting ourselves in a bad position.
