### ISSUE TITLE
Family photos

### ISSUE THREAD

**Issue by goldygolden** [GreenfieldMC/Greenfield-Texturepack#40]
A painting that has a family on it, could be used in houses etc

One of existing paintings or one of the new ones

![image](https://user-images.githubusercontent.com/92544704/179313794-66f34478-8b80-459d-af4f-051afb404246.png)

Preferebly on a 1x1 painting but whatever size is fine

**Comment by NJDaeger** [comment]
Related to the new paintings from 1.19. All four will be done, this will be considered for one of them

**Comment by NJDaeger** [comment]
This is now done
