### ISSUE TITLE
Beams

### ISSUE THREAD

**Issue by goldygolden** [GreenfieldMC/Greenfield-Texturepack#41]
The amathyst crystals

https://www.google.nl/url?sa=i&url=https%3A%2F%2Fwww.woodsolutions.com.au%2Fwood-species%2Fwood-products%2Fi-beams&psig=AOvVaw1Sb9JyaWcfGmL5sydSjumc&ust=1666292993958000&source=images&cd=vfe&ved=0CA0QjRxqFwoTCMj63KH_7PoCFQAAAAAdAAAAABAE 

This might be impossible but you guys changed dead coral into trash cans so who knows, Since the amathyst crystal sits on the roof and floor the different levels of coral could be different wood colours or metal

**Comment by NJDaeger** [comment]
this is pretty much being handled in 1.20 and already has been added to the amethyst crystals
