### ISSUE TITLE
Wool saturation

### ISSUE THREAD

**Issue by titonix** [GreenfieldMC/Greenfield-Texturepack#44]
Make the wool less saturated it hurts my eyes
![black_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/2e378dc0-aec5-4fe3-91e6-d0dc4ba906e0)
![blue_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/e3c67cf7-5c9f-4b14-891d-b72c992612dd)
![brown_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/28115b77-2e0e-42b0-bef3-cdabdccf64b8)
![cyan_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/7856b222-2b10-4d77-b6af-d01c74d67121)
![gray_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/e06e9e19-5edd-4304-a3bc-f66b7eac8a8d)
![green_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/eedd5884-2299-4d3b-a8dc-7f8143742337)
![light_blue_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/ae7a12e0-f0ab-45ce-bb97-ee4204d41b6a)
![light_gray_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/5c3817b2-ecbc-4225-8bf1-309395ae870c)
![lime_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/61100e50-2f87-4a27-9f8d-9a07ef30d3b0)
![magenta_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/3f5c2465-56fe-4322-b8cb-b81f8b53790e)
![orange_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/c749ff3a-5030-49fd-8044-5535e79cacb8)
![pink_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/6cd78729-b268-4822-a2f8-49bb6e680913)
![purple_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/eb555235-f5da-43cb-b3e9-8578f5e101f3)
![red_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/cabc9865-275b-4342-b480-89f0be8018c4)
![white_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/924dbb5b-7792-43ca-b547-e9da9a142a76)
![yellow_wool](https://github.com/GreenfieldMC/Greenfield-Texturepack/assets/70404195/1da9d80b-d3a2-4444-99bb-c21b6de7f731)
Sorry i couldnt figure out how to do a pull request

**Comment by NJDaeger** [comment]
Hi, thanks for making the issue, we have done some minor adjustments to wool in the coming resourcepack update, but we don't have plans to redo all of them to be less saturated. The alternative for less saturated wools is the terracotta blocks - they are the exact same texture just toned down
