### ISSUE TITLE
exent the spigot model

### ISSUE THREAD

**Issue by emmatoocold** [GreenfieldMC/Greenfield-Texturepack#66]
extend the spigot model 2 pixels into the block it sits against. trapdoors are 3 pixels thick so it wouldn't cause z fighting issues when connected against them but It could connect to blocks that are 2 px shorter than a full m^3.

![2024-08-09_07 49 31](https://github.com/user-attachments/assets/3b713769-ec91-4e1e-9d8c-e34a21889ea6)

**Comment by Stapelo** [comment]
This has been added.
