### ISSUE TITLE
Custom Sticky Piston side texture

### ISSUE THREAD

**Issue by JacobKazias** [GreenfieldMC/Greenfield-Texturepack#7]
**What is the texture you would like added?**
Custom sticky piston side texture (requires model).

**Should this texture be based on an existing block? If so, what block?**
Piston/Sticky Piston

**Provide an image reference of the material/texture being used in real life. (More than one, if possible)**
N/A

**Additional context**
Currently both pistons share all the same textures besides the top.

**Comment by NJDaeger** [comment]
Wasn't this just done?

**Comment by JacobKazias** [comment]
> Wasn't this just done?

We weren't originally planning on doing it right away but yes this is now done, will close the issue.
